USE [master]
GO

/****** Object:  Database [crypto]    Script Date: 14/02/2020 11:45:35 ******/
CREATE DATABASE [crypto]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'crypto', FILENAME = N'/var/opt/mssql/data/crypto.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'crypto_log', FILENAME = N'/var/opt/mssql/data/crypto_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [crypto].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [crypto] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [crypto] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [crypto] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [crypto] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [crypto] SET ARITHABORT OFF 
GO

ALTER DATABASE [crypto] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [crypto] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [crypto] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [crypto] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [crypto] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [crypto] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [crypto] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [crypto] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [crypto] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [crypto] SET  DISABLE_BROKER 
GO

ALTER DATABASE [crypto] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [crypto] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [crypto] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [crypto] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [crypto] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [crypto] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [crypto] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [crypto] SET RECOVERY FULL 
GO

ALTER DATABASE [crypto] SET  MULTI_USER 
GO

ALTER DATABASE [crypto] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [crypto] SET DB_CHAINING OFF 
GO

ALTER DATABASE [crypto] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [crypto] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [crypto] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [crypto] SET QUERY_STORE = OFF
GO

ALTER DATABASE [crypto] SET  READ_WRITE 
GO


